import { getMiniGameLeaderboard, submitMiniGameScore } from '../../../lib/homeExperienceApi';
import React, { useMemo, useState } from 'react';
const shuffle=(items)=>[...items].sort(()=>Math.random()-.5);
export default function ToneSwitcherGame({ctx,game}){
 const {gamePhase,setGamePhase}=ctx;
 const [session,setSession]=useState([]),[index,setIndex]=useState(0),[choiceId,setChoiceId]=useState(''),[reports,setReports]=useState([]),[locked,setLocked]=useState(false);
 const [playerName,setPlayerName]=useState(''),[board,setBoard]=useState([]),[boardOpen,setBoardOpen]=useState(false),[standing,setStanding]=useState(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[startedAt,setStartedAt]=useState(0);
 const c=session[index], choice=c?.options?.find(x=>x.id===choiceId);
 const total=reports.reduce((s,x)=>s+x.score,0);
 const avg=useMemo(()=>{if(!reports.length)return{toneFit:0,audienceFit:0,clarity:0};return{toneFit:Math.round(reports.reduce((s,x)=>s+x.toneFit,0)/reports.length),audienceFit:Math.round(reports.reduce((s,x)=>s+x.audienceFit,0)/reports.length),clarity:Math.round(reports.reduce((s,x)=>s+x.clarity,0)/reports.length)}},[reports]);
 const start=()=>{const pool=(game?.cases||[]).filter(x=>x?.enabled!==false);setSession(shuffle(pool).slice(0,Math.min(Number(game?.casesPerSession)||10,pool.length)));setIndex(0);setChoiceId('');setReports([]);setLocked(false);setStartedAt(Date.now());setStanding(null);setNotice('');setGamePhase('tone-play')};
 const submit=()=>{if(!choice||locked)return;setReports(p=>[...p,{...choice,score:Number(choice.toneFit||0)+Number(choice.audienceFit||0)+Number(choice.clarity||0)}]);setLocked(true)};
 const next=()=>{if(index>=session.length-1){setGamePhase('tone-result');return}setIndex(v=>v+1);setChoiceId('');setLocked(false)};
 const activeSeconds=startedAt?Math.max(0,Math.floor((Date.now()-startedAt)/1000)):0;const refreshBoard=async()=>{try{setBoard(await getMiniGameLeaderboard('tone-switcher',20));setBoardOpen(true)}catch{setNotice('Klasemen belum dapat dimuat.')}};const save=async()=>{if(playerName.trim().length<2){setNotice('Nama / alias minimal 2 karakter.');return}setSaving(true);try{const accuracy=Math.round(total/Math.max(1,session.length*100)*100);const st=await submitMiniGameScore({gameId:'tone-switcher',playerName,score:total,accuracy,correctCount:reports.filter(x=>x.score>=90).length,totalQuestions:session.length,activeSeconds});setStanding(st);setNotice('');await refreshBoard()}catch{setNotice('Skor belum dapat disimpan.')}finally{setSaving(false)}};const grade=(game?.gradeTitles||[]).slice().sort((a,b)=>Number(b.min)-Number(a.min)).find(g=>total>=Number(g.min))||{label:'Wrong Room',remark:''};
 const strongest=Object.entries(avg).sort((a,b)=>b[1]-a[1])[0]?.[0]; const strongestLabel=strongest==='toneFit'?game?.toneFitLabel:strongest==='audienceFit'?game?.audienceFitLabel:game?.clarityLabel;
 if(gamePhase==='tone-intro')return <section className="mx-auto max-w-3xl py-6"><button onClick={()=>setGamePhase('library')} className="mb-5 min-h-11 rounded border border-gray-300 px-4 py-2 font-mono text-xs font-bold uppercase dark:border-gray-600">← Balik ke Menu Games</button><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#2B579A]">{game?.gameCategory}</p><p className="mt-4 max-w-2xl font-serif text-lg leading-relaxed text-gray-700 dark:text-gray-200">{game?.objective}</p><div className="mt-6 overflow-hidden rounded border border-gray-300 dark:border-gray-700">{(game?.rules||[]).map((r,i)=><div key={i} className="grid grid-cols-[3.25rem_1fr] border-b border-gray-200 last:border-b-0 dark:border-gray-700"><div className="grid place-items-center bg-gray-50 py-4 font-mono text-xs font-bold text-[#2B579A] dark:bg-white/5">{String(i+1).padStart(2,'0')}</div><p className="px-4 py-4 text-sm leading-relaxed">{r}</p></div>)}</div><button onClick={start} className="mt-6 min-h-11 rounded bg-[#2B579A] px-5 py-2.5 text-sm font-bold text-white">{game?.startButtonLabel}</button></section>;
 if(gamePhase==='tone-play'&&c)return <section className="mx-auto max-w-4xl py-5"><div className="mb-4 flex justify-between font-mono text-[10px] font-bold uppercase tracking-[.16em] text-gray-500"><span>{game?.contextLabel} {String(index+1).padStart(2,'0')} / {String(session.length).padStart(2,'0')}</span><span>{c.label}</span></div><div className="grid gap-3 md:grid-cols-3">{[[game?.channelLabel,c.channel],[game?.audienceLabel,c.audience],[game?.toneLabel,c.targetTone]].map(([l,v])=><div key={l} className="rounded border border-gray-300 bg-white p-4 dark:border-gray-700 dark:bg-[#252525]"><span className="font-mono text-[9px] font-bold uppercase tracking-wider text-[#2B579A]">{l}</span><p className="mt-2 text-sm">{v}</p></div>)}</div><div className="mt-3 rounded border border-gray-300 bg-gray-50 p-4 dark:border-gray-700 dark:bg-white/5"><span className="font-mono text-[9px] font-bold uppercase tracking-wider text-gray-500">{game?.sourceLabel}</span><p className="mt-2 font-serif text-lg">{c.source}</p></div><p className="mb-3 mt-6 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-gray-500">{game?.chooseLabel}</p><div className="grid gap-3 md:grid-cols-2">{c.options.map(o=><button disabled={locked} key={o.id} onClick={()=>setChoiceId(o.id)} className={`min-h-[112px] rounded border p-4 text-left text-sm leading-relaxed transition ${choiceId===o.id?'border-[#2B579A] bg-blue-50 ring-1 ring-[#2B579A] dark:bg-blue-950/30':'border-gray-300 bg-white hover:border-[#2B579A] dark:border-gray-700 dark:bg-[#252525]'}`}>{o.text}</button>)}</div>{!locked&&<button disabled={!choiceId} onClick={submit} className="mt-5 min-h-11 rounded bg-[#2B579A] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-40">{game?.submitLabel}</button>}{locked&&choice&&<div className="mt-6 rounded border border-gray-300 bg-white p-5 dark:border-gray-700 dark:bg-[#252525]"><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#2B579A]">{game?.reportLabel}</p><p className="mt-3 font-serif text-xl">{choice.text}</p><div className="mt-5 grid grid-cols-3 gap-3">{[[game?.toneFitLabel,choice.toneFit,40],[game?.audienceFitLabel,choice.audienceFit,35],[game?.clarityLabel,choice.clarity,25]].map(([l,v,m])=><div key={l} className="rounded border border-gray-200 p-3 text-center dark:border-gray-700"><span className="block font-mono text-[9px] font-bold uppercase text-gray-500">{l}</span><strong className="mt-1 block text-lg">{v}/{m}</strong></div>)}</div><button onClick={next} className="mt-5 min-h-11 rounded border border-[#2B579A] px-5 py-2.5 text-sm font-bold text-[#2B579A]">{index>=session.length-1?'Lihat Hasil':game?.nextLabel}</button></div>}</section>;
 if(gamePhase==='tone-result')return <section className="mx-auto max-w-3xl py-8"><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#2B579A]">{game?.resultEyebrow}</p><h3 className="mt-2 font-serif text-3xl">{grade.label}</h3><p className="mt-2 text-sm text-gray-600 dark:text-gray-300">{grade.remark}</p><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">{[[game?.scoreLabel,total,session.length*100],[game?.toneFitLabel,avg.toneFit,40],[game?.audienceFitLabel,avg.audienceFit,35],[game?.clarityLabel,avg.clarity,25]].map(([l,v,m])=><div key={l} className="rounded border border-gray-300 p-4 dark:border-gray-700"><span className="font-mono text-[9px] uppercase text-gray-500">{l}</span><strong className="mt-1 block text-2xl">{v}/{m}</strong></div>)}</div><p className="mt-4 text-sm"><strong>{game?.bestDimensionLabel}:</strong> {strongestLabel}</p><div className="mt-6 max-w-md"><label className="text-xs font-bold uppercase">Nama / alias</label><input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder="Nama / alias" className="mt-2 w-full rounded border border-gray-300 bg-transparent px-3 py-2 dark:border-gray-600"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={save} disabled={saving} className="min-h-11 rounded bg-[#2B579A] px-4 py-2 text-sm font-bold text-white">{saving?'Menyimpan…':'Simpan Skor'}</button><button onClick={start} className="min-h-11 rounded border border-gray-300 px-4 py-2 text-sm font-semibold dark:border-gray-700">{game?.replayLabel}</button><button onClick={refreshBoard} className="min-h-11 rounded border border-gray-300 px-4 py-2 text-sm font-semibold dark:border-gray-700">Lihat Klasemen</button><button onClick={()=>setGamePhase('library')} className="min-h-11 rounded border border-gray-300 px-4 py-2 text-sm font-semibold dark:border-gray-700">Balik ke Menu Games</button></div>{standing&&<p className="mt-3 text-sm">Peringkat Anda: <strong>#{standing.rank||'—'}</strong></p>}{notice&&<p className="mt-2 text-xs text-red-600">{notice}</p>}{boardOpen&&<div className="mt-6"><div className="flex items-center justify-between"><h4 className="font-serif text-xl">Klasemen</h4><button onClick={()=>setBoardOpen(false)} className="text-xs">Tutup ×</button></div><div className="mt-3 space-y-2">{board.map((row,i)=><div key={row.id||i} className="grid grid-cols-[2rem_1fr_auto] gap-3 border-b border-gray-200 py-2 text-sm dark:border-gray-700"><strong>#{i+1}</strong><span>{row.playerName}</span><span>{row.score}</span></div>)}</div></div>}</div></section>;
 return null;
}